// import Navbar from "@/components/Navbar";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.css"; // Import FontAwesome CSS
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body>
        {/* <Navbar /> */}

        {children}
      </body>
    </html>
  );
}
